name: test
on: 
  push:
      branches: main
  workflow_dispatch:
#  schedule:
#    - cron: 0 16 * * *
jobs:
    Copy_Push:
        runs-on: ubuntu-18.04
        steps:
          - name: Checkout repo
            uses: actions/checkout@v2
          - name: Download files needed
            run: |
              mkdir -p /opt/shaolin-kongfu/zq/ && mkdir -p /opt/shaolin-kongfu/jc/
              git clone "https://github.com/shaolin-kongfu/js_scripts.git" "/opt/shaolin-kongfu/js_scripts/"
          - name: Modify files
            run: |
              find /opt/shaolin-kongfu/js_scripts/zq -name "dsj.js" | xargs -I {} cp {} /opt/shaolin-kongfu/zq/
              find /opt/shaolin-kongfu/js_scripts/zq -name "*.json" | xargs -I {} cp {} /opt/shaolin-kongfu/zq/
              find /opt/shaolin-kongfu/js_scripts/ -name "*jc*.json" | xargs -I {} cp {} /opt/shaolin-kongfu/jc/
              find /opt/shaolin-kongfu/zq/ -type f | xargs -I {} sed -i 's#raw.githubusercontent.com#ghproxy.com/https://raw.githubusercontent.com#g' {}
              find /opt/shaolin-kongfu/jc/ -type f | xargs -I {} sed -i 's#raw.githubusercontent.com#ghproxy.com/https://raw.githubusercontent.com#g' {}
          - name: Send back
            run: |
              cp -fr /opt/shaolin-kongfu/zq/* "${GITHUB_WORKSPACE}/"
              cp -fr /opt/shaolin-kongfu/jc/* "${GITHUB_WORKSPACE}/"
              ls

          - name: Commit files
            run: |
              git config --local user.email "test@qq.com"
              git config --local user.name "test"
              git branch test
              git checkout test
              git add *
              git commit -m "update" -a
          - name: Push changes
            uses: ad-m/github-push-action@master
            with:
              github_token: ${{ secrets.GITHUB_TOKEN }}
              branch: 'test'
              force: true
