name: test
on: 
  push:
      branches: main
  workflow_dispatch:
  schedule:
    - cron: 0 17 * * *
jobs:
    Copy_Push:
        runs-on: ubuntu-18.04
        steps:
          - name: Checkout repo
            uses: actions/checkout@v2
          - name: download
            run: |
              mkdir -p /opt/shaolin/ & mkdir -p /opt/shaolin-back/
              git clone "https://github.com/shaolin-kongfu/js_scripts.git" "/opt/shaolin/"
              mkdir -p /opt/soy-tool/ & mkdir -p /opt/soy-tool-back/
              git clone "https://gitee.com/soy-tool/app-script.git" "/opt/soy-tool/"
          - name: find
            run: |
              find /opt/shaolin/ -name "*jc*.json" | xargs -I {} cp {} /opt/shaolin-back/
              find /opt/soy-tool/ -name "*.js" | xargs -I {} cp {} /opt/soy-tool-back/
          - name: Send back
            run: |
              mkdir -p "${GITHUB_WORKSPACE}/shaolin-back" && cp -rf /opt/soy-tool-back/* "${GITHUB_WORKSPACE}/shaolin-back"
              mkdir -p "${GITHUB_WORKSPACE}/soy-tool-back" && cp -rf /opt/soy-tool-back/* "${GITHUB_WORKSPACE}/soy-tool-back"
          - name: Commit files
            run: |
              git config --local user.email "test@qq.com"
              git config --local user.name "test"
              git pull 
              git checkout origin/test
              git add *
              git commit -m "update" -a
          - name: Push changes
            uses: ad-m/github-push-action@master
            with:
              github_token: ${{ secrets.GITHUB_TOKEN }}
              branch: 'test'
              # force: true
